version: "3.9":wq!
services:
  db:
    image: postgres
    ports:
      - '5434:5432'
    environment:
      - POSTGRES_DB=tgt_postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
